### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by invas10n01** [invas10n01/mpvc#1]
## TODO
- [ ] Code cleaning

- [ ] Better cover sizing and positioning config
<pre>
* Flexible ASCII Cover (Auto adjust size by cover_size)
</pre>

- [ ] Intregration with youtube

- [ ] Handle exact same lyrics lines in multi_lrc mode
<pre>
* i.e. LRC line: [01:20.15] Zzz... ─┐
                 [01:23.35] Zzz...  ├─ Merging these line like [01:20.15] Zzz... (x3)
                 [01:25.35] Zzz... ─┘                          [01:30.33] ABc...
                 [01:30.33] ABc...
</pre>

- [ ] Proper way to close mpvc_sub and track_info descendents without using pkill

- [ ] Cover Loading Theme for Big Size Cover

- [ ] MPV socket control without mpvctl

- [ ] Fix history keyword load postion in big size cover

- [ ] Auto remove non-media files from the playlist

- [ ] Improve db_search func
<pre>
* Working with fzf_init_search
</pre>

- [ ] Searching with [beets](https://github.com/beetbox/beets) database

- [ ] User define color for fzf

- [ ] Merge some part of mpvc-pinfo.sh to mpvc-pinfo.lua

- [ ] Fix tmux screen mess up when close cava on the vertical pane

- [ ] Wraping lrc_conv lines for terminal screen

- [ ] Coloring tmux statusbar

- [ ] Better pick_ucolor algorithm
<pre>
* If lyrics focus ucolor is too dark, change color to readable/bright color
</pre>

- [ ] Display track_info without while loop
<pre>
* Use fifo for draw_pbar
</pre>

- [ ] Handle with overtime LRC line
<pre>
* i.e. Media playtime : 3 min 20 s
             LRC line : [03:50.15] Zzz...
</pre>

- [ ] Mood by color
<pre>
* Kind of mood tag, but present color for each music's feeling
</pre>

- [ ] More useful information on fzf preview line

- [ ] Better fix_lrc algorithm
- [ ] Suppress kill message when ueberzug_fifo removed
- [ ] Load LRC from preset directory
- [ ] Use database instead file caches
- [ ] Prevent exec string cutting after db_search empty input
- [ ] Check compatibility in other environment
- [ ] Check /mnt/ drive mount status
- [ ] Command input mode (i.e. > shuffle)?

- [x] Sync album_ucolors with fzf colorscheme
- [x] Merge mpvctl_fzf_remove to mpvctl_fzf_play
<pre>
* fzf mode switch bind key d
</pre>
- [x] Use fifo for better subtitle sync accuracy
- [x] Fix the sync problem when mpvctl cmd executed from outside
- [x] Support more subtitle formats
<pre>
* For the case like just listening media with subtitle and without video
</pre>
- [x] Play music when select lrc file in fzf_sel
- [x] Replace cursor movement expressions
